### ISSUE TITLE
Deployment error - ConsumerLambdaFunction validation error

### ISSUE THREAD

**Issue by mrameezraja** [bahrmichael/aws-scheduler#6]
Hey @bahrmichael ,

Thanks for sharing this piece of code. I am trying to deploy but it's giving me attached error.
![image](https://user-images.githubusercontent.com/8121938/126900679-0577eb11-8c28-46ee-9e00-406ec91302f3.png)

I tried everything within my knowledge as i am from C# background, but nothing is working.

Thanks,

**Comment by bahrmichael** [comment]
hi, thanks for reaching out!

> I tried everything within my knowledge

What did you try already? How did you deploy it? What version of serverless framework do you use?

Cheers

**Comment by mrameezraja** [comment]
Hey,
So i followed the setup steps and was able to create, table, queue and sns topics, input, output and failure. Everything worked fine. But when i try to deploy, it gives above error. I even tried changing code to pass consumer_handle(json.dumps(items)) here:
![image](https://user-images.githubusercontent.com/8121938/126958995-6be1050f-2e31-4741-916d-d8dab2c4a7ba.png)

But still it gives same error for both functions. consumer and emitter.

Here are the serverless version details.
![image](https://user-images.githubusercontent.com/8121938/126958337-7f2d7671-80c2-4b38-96df-ccf7331ac873.png)

Thanks,

**Comment by bahrmichael** [comment]
I wrote the scheduler with sls framework 1.x, and I assume there has been a change in the way we have to write tags. You can try using sls framework 1.x, or remove the tags (e.g. https://github.com/bahrmichael/aws-scheduler/blob/master/serverless.yml#L71) from the `serverless.yml` file.

Let me know if that helps :)

**Comment by mrameezraja** [comment]
removing tags didn't help. Still same issue.

![image](https://user-images.githubusercontent.com/8121938/127168144-34fd7ac6-7e94-49cb-9856-d64992d866fb.png)

![image](https://user-images.githubusercontent.com/8121938/127168086-7652d0f7-8fb7-4847-ac00-be501da2b2be.png)

**Comment by mrameezraja** [comment]
So finally i managed to deploy by removing tags and this line too.
https://github.com/bahrmichael/aws-scheduler/blob/master/serverless.yml#L10

Thanks,

**Comment by bahrmichael** [comment]
Thank you for sharing this :)
